{
  imports = [
    ./auto-pairs.nix
    ./auto-save.nix
    ./codesnap.nix
    ./comments.nix
    ./cursorline.nix
    ./diffview.nix
    ./gitsigns.nix
    ./indent-blankline.nix
    ./lazygit.nix
    ./noice.nix
    ./telescope.nix
    ./todo.nix
    ./toggleterm.nix
    ./undotree.nix
    #./vimtex.nix
    ./vim-tmux-navigator.nix
    ./which-key.nix
    ./wilder.nix
    ./yazi.nix
  ];
}
