{
  imports = [
    ./auto-pairs.nix
    ./auto-save.nix
    ./comments.nix
    ./cursorline.nix
    ./gitsigns.nix
    ./indent-blankline.nix
    ./noice.nix
    ./telescope.nix
    ./todo.nix
    ./toggleterm.nix
    ./undotree.nix
    ./vimtex.nix
    ./vim-tmux-navigator.nix
    ./which-key.nix
    ./wilder.nix
  ];
}
